apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier
  labels:
    app: backend-app
data:
  DB_HOST: mysql-svc #service name of mysql
  DB_NAME: school
  DB_PORT: "3306"
