apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: three-tier
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRtRnljMmhwZEdoaGEybzZkbUZ5YzJocE1USXoiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
