apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-app-ingress
  namespace: three-tier
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: student-app.local
    http:
      paths:
        # Frontend React App
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000
        # Backend APIs
        - path: /student
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 3500
        - path: /teacher
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 3500
        