apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.names.pv }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.volumeStorage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/db
    type: DirectoryOrCreate