apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: {{ .Values.namespace }}
data:
  {{ if .Values.password }}
  password: {{ .Values.password }}
  {{ end }}
  {{ if .Values.user }}
  user: {{ .Values.user }}  
  {{ end }}