apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mysql-db.selectorLabels" . | nindent 6 }}
