apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysql-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql-db.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
          env:
          - name: MYSQL_DATABASE
            value: {{ .Values.databaseName }}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.names.secret }}
                key: {{ .Values.mysqlRootPasswordkey }}
          volumeMounts:
            - name: {{ .Values.names.volumeName }}
              mountPath: /var/lib/mysql
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes: 
      - name: {{ .Values.names.volumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.names.pvc }}     
          
      
