apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.names.configMap }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backend-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.DB_HOST }}
  DB_NAME: {{ .Values.DB_NAME }}
  DB_PORT: "{{ .Values.DB_PORT }}"