# Default values for mysql-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
names:
  deployment: mysql-deployment
  service: mysql-svc
  secret: mysql-secret
  volumeName: mysql-volume
  pvc: mysql-volume-claim  
  pv: mysql-pv
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

replicaCount: 1
namespace: three-tier


# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: 8.0

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  existingSecret: docker-registry-secret

# This is to override the chart name.
fullnameOverride: mysql-deployment

#environment values
databaseName: school
mysqlRootPasswordkey: password
password: bXlzcWwxMjM=
user: cm9vdA==  
volumeStorage: 1Gi
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  port: 3306
  targetPort: 3306
  

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
startupProbe:
  exec:
    command:
    - sh
    - -c
    - "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 30
readinessProbe:
  exec:
    command:
    - sh
    - -c
    - "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"
  initialDelaySeconds: 10
  periodSeconds: 10


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

